// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-cours'}],
  tps: [{type: 'autogenerated', dirName: '02-tps'}],
};

module.exports = sidebars;
